export const SUBTITLE_STYLES = {
  hormozi: {
    id: 'hormozi',
    name: 'Hormozi',
    fontFamily: 'Montserrat, sans-serif',
    fontNameFallback: 'IBM Plex Sans, sans-serif',
    fontSize: 105,
    primaryColor: '#FFFFFF',
    highlightColor: '#00FFFF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    shadowAlpha: 128,
    outlineSize: 5.0,
    shadowDepth: 4.5,
    bold: true,
    italic: false,
    letterSpacing: 0,
    wordSpacing: 100,
    animationType: 'highlight',
    bestFor: 'Business & motivation',
  },
  mrbeast: {
    id: 'mrbeast',
    name: 'MrBeast',
    fontFamily: 'Bangers, sans-serif',
    fontNameFallback: 'IBM Plex Sans, sans-serif',
    fontSize: 120,
    primaryColor: '#FFFFFF',
    highlightColor: '#FFD700',
    outlineColor: '#000000',
    shadowColor: '#000000',
    shadowAlpha: 0,
    outlineSize: 8.0,
    shadowDepth: 6.0,
    bold: true,
    italic: false,
    letterSpacing: 0,
    wordSpacing: 100,
    animationType: 'bounce',
    bestFor: 'Gaming & entertainment',
  },
  karaoke: {
    id: 'karaoke',
    name: 'Karaoke',
    fontFamily: 'Montserrat, sans-serif',
    fontNameFallback: 'IBM Plex Sans, sans-serif',
    fontSize: 105,
    primaryColor: '#FFFFFF',
    highlightColor: '#FFD700',
    outlineColor: '#000000',
    shadowColor: '#000000',
    shadowAlpha: 128,
    outlineSize: 4.0,
    shadowDepth: 3.0,
    bold: true,
    italic: false,
    letterSpacing: 0,
    wordSpacing: 100,
    animationType: 'karaoke',
    bestFor: 'Music & sing-alongs',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    fontFamily: 'Bebas Neue, sans-serif',
    fontNameFallback: 'IBM Plex Sans, sans-serif',
    fontSize: 120,
    primaryColor: '#FFFFFF',
    highlightColor: '#F5F5F5',
    outlineColor: '#000000',
    shadowColor: '#000000',
    shadowAlpha: 128,
    outlineSize: 4.0,
    shadowDepth: 3.0,
    bold: true,
    italic: true,
    letterSpacing: 3.0,
    wordSpacing: 110,
    animationType: 'scale',
    bestFor: 'Professional & clean',
  },
  wordpop: {
    id: 'wordpop',
    name: 'Word Pop',
    fontFamily: 'Montserrat, sans-serif',
    fontNameFallback: 'IBM Plex Sans, sans-serif',
    fontSize: 105,
    primaryColor: '#FFFFFF',
    highlightColor: '#00FFFF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    shadowAlpha: 128,
    outlineSize: 5.0,
    shadowDepth: 4.5,
    bold: true,
    italic: false,
    letterSpacing: 0,
    wordSpacing: 100,
    animationType: 'wordpop',
    bestFor: 'TikTok & viral content',
  },
  simple: {
    id: 'simple',
    name: 'Simple',
    fontFamily: 'Montserrat, sans-serif',
    fontNameFallback: 'IBM Plex Sans, sans-serif',
    fontSize: 105,
    primaryColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    shadowAlpha: 128,
    outlineSize: 4.0,
    shadowDepth: 0,
    bold: true,
    italic: false,
    letterSpacing: 0,
    wordSpacing: 100,
    animationType: 'simple',
    bestFor: 'Podcast & conversation',
  },
  popline: {
    id: 'popline',
    name: 'Pop Line',
    fontFamily: 'Montserrat, sans-serif',
    fontNameFallback: 'IBM Plex Sans, sans-serif',
    fontSize: 105,
    primaryColor: '#FFFFFF',
    highlightColor: '#9B30FF',
    outlineColor: '#000000',
    shadowColor: '#000000',
    shadowAlpha: 128,
    outlineSize: 4.0,
    shadowDepth: 3.0,
    bold: true,
    italic: false,
    letterSpacing: 0,
    wordSpacing: 100,
    animationType: 'popline',
    bestFor: 'Viral & trending content',
  },
}

export const SUBTITLE_POSITIONS = {
  top: {
    id: 'top',
    name: 'TOPO',
    justifyContent: 'flex-start',
    paddingTop: '20px',
  },
  middle: {
    id: 'middle',
    name: 'MEIO',
    justifyContent: 'center',
    paddingTop: '0',
  },
  bottom: {
    id: 'bottom',
    name: 'BAIXO',
    justifyContent: 'flex-end',
    paddingBottom: '40px',
  },
}

export const SUBTITLE_STYLE_LIST = Object.values(SUBTITLE_STYLES)
export const SUBTITLE_POSITION_LIST = Object.values(SUBTITLE_POSITIONS)
